export type AchievementCategory = 'purchase' | 'social' | 'gaming' | 'loyalty' | 'referral' | 'seasonal' | 'hidden';
export type AchievementRarity = 'common' | 'uncommon' | 'rare' | 'epic' | 'legendary';

export interface Achievement {
  id: string;
  name: string;
  description: string;
  category: AchievementCategory;
  rarity: AchievementRarity;
  emoji: string;
  xpReward: number;
  pointReward: number;
  isSecret: boolean;
  isCrossPlatform: boolean;
  isSeasonal: boolean;
  unlockedCount: number;
  totalEligible: number;
  unlockRate: number;
  createdAt: string;
}

export const RARITY_CONFIG: Record<AchievementRarity, { label: string; color: string; bg: string }> = {
  common:    { label: 'Common',    color: '#94A3B8', bg: '#94A3B820' },
  uncommon:  { label: 'Uncommon', color: '#34D399', bg: '#34D39920' },
  rare:      { label: 'Rare',     color: '#60A5FA', bg: '#60A5FA20' },
  epic:      { label: 'Epic',     color: '#A78BFA', bg: '#A78BFA20' },
  legendary: { label: 'Legendary',color: '#FBBF24', bg: '#FBBF2420' },
};

export const DEMO_ACHIEVEMENTS: Achievement[] = [
  {
    id: 'ach_first_cop',
    name: 'First Cop',
    description: 'Complete your first order on any platform.',
    category: 'purchase',
    rarity: 'common',
    emoji: '👟',
    xpReward: 100,
    pointReward: 200,
    isSecret: false,
    isCrossPlatform: false,
    isSeasonal: false,
    unlockedCount: 28410,
    totalEligible: 42300,
    unlockRate: 67.2,
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'ach_heat_seeker',
    name: 'Heat Seeker',
    description: 'Purchase 5 limited-edition releases.',
    category: 'purchase',
    rarity: 'uncommon',
    emoji: '🔥',
    xpReward: 500,
    pointReward: 1000,
    isSecret: false,
    isCrossPlatform: false,
    isSeasonal: false,
    unlockedCount: 4820,
    totalEligible: 28410,
    unlockRate: 17.0,
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'ach_whale',
    name: 'The Whale',
    description: 'Spend over ₹100,000 across all platforms.',
    category: 'purchase',
    rarity: 'rare',
    emoji: '🐋',
    xpReward: 2000,
    pointReward: 5000,
    isSecret: false,
    isCrossPlatform: true,
    isSeasonal: false,
    unlockedCount: 312,
    totalEligible: 42300,
    unlockRate: 0.74,
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'ach_connector',
    name: 'The Connector',
    description: 'Refer 10 friends who complete their first purchase.',
    category: 'referral',
    rarity: 'rare',
    emoji: '🕸️',
    xpReward: 1500,
    pointReward: 3000,
    isSecret: false,
    isCrossPlatform: false,
    isSeasonal: false,
    unlockedCount: 892,
    totalEligible: 42300,
    unlockRate: 2.1,
    createdAt: '2026-01-15T00:00:00Z',
  },
  {
    id: 'ach_ambassador',
    name: 'Ambassador',
    description: 'Refer 50 friends. Your network is your legacy.',
    category: 'referral',
    rarity: 'epic',
    emoji: '👑',
    xpReward: 10000,
    pointReward: 25000,
    isSecret: false,
    isCrossPlatform: false,
    isSeasonal: false,
    unlockedCount: 28,
    totalEligible: 42300,
    unlockRate: 0.07,
    createdAt: '2026-01-15T00:00:00Z',
  },
  {
    id: 'ach_streak_30',
    name: 'Iron Streak',
    description: 'Maintain a 30-day activity streak.',
    category: 'loyalty',
    rarity: 'rare',
    emoji: '⚡',
    xpReward: 3000,
    pointReward: 2000,
    isSecret: false,
    isCrossPlatform: false,
    isSeasonal: false,
    unlockedCount: 1240,
    totalEligible: 42300,
    unlockRate: 2.9,
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'ach_streak_100',
    name: 'Century Streak',
    description: 'Maintain a 100-day activity streak without a break.',
    category: 'loyalty',
    rarity: 'legendary',
    emoji: '💯',
    xpReward: 20000,
    pointReward: 10000,
    isSecret: false,
    isCrossPlatform: false,
    isSeasonal: false,
    unlockedCount: 7,
    totalEligible: 42300,
    unlockRate: 0.02,
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'ach_night_owl',
    name: 'Night Owl',
    description: 'Make 20 purchases between 00:00–04:00 UTC.',
    category: 'hidden',
    rarity: 'uncommon',
    emoji: '🦉',
    xpReward: 800,
    pointReward: 1500,
    isSecret: true,
    isCrossPlatform: false,
    isSeasonal: false,
    unlockedCount: 2140,
    totalEligible: 42300,
    unlockRate: 5.1,
    createdAt: '2026-02-01T00:00:00Z',
  },
  {
    id: 'ach_diwali_champion',
    name: 'Diwali Champion',
    description: 'Finish #1 on the Diwali Sneaker Rush leaderboard.',
    category: 'seasonal',
    rarity: 'legendary',
    emoji: '🪔',
    xpReward: 50000,
    pointReward: 25000,
    isSecret: false,
    isCrossPlatform: false,
    isSeasonal: true,
    unlockedCount: 1,
    totalEligible: 42300,
    unlockRate: 0.002,
    createdAt: '2026-10-01T00:00:00Z',
  },
  {
    id: 'ach_cross_platform',
    name: 'Ecosystem Citizen',
    description: 'Be active on all 4 PlayR platforms in a single week.',
    category: 'social',
    rarity: 'epic',
    emoji: '🌐',
    xpReward: 5000,
    pointReward: 5000,
    isSecret: false,
    isCrossPlatform: true,
    isSeasonal: false,
    unlockedCount: 142,
    totalEligible: 42300,
    unlockRate: 0.34,
    createdAt: '2026-03-01T00:00:00Z',
  },
  {
    id: 'ach_game_grinder',
    name: 'Game Grinder',
    description: 'Complete 100 matches on PlayR Game.',
    category: 'gaming',
    rarity: 'uncommon',
    emoji: '🎮',
    xpReward: 1000,
    pointReward: 800,
    isSecret: false,
    isCrossPlatform: false,
    isSeasonal: false,
    unlockedCount: 3241,
    totalEligible: 12000,
    unlockRate: 27.0,
    createdAt: '2026-03-01T00:00:00Z',
  },
  {
    id: 'ach_apex_climber',
    name: 'APEX Climber',
    description: 'Reach APEX tier. You are in the top 0.7%.',
    category: 'loyalty',
    rarity: 'legendary',
    emoji: '🏔️',
    xpReward: 30000,
    pointReward: 15000,
    isSecret: false,
    isCrossPlatform: false,
    isSeasonal: false,
    unlockedCount: 312,
    totalEligible: 42300,
    unlockRate: 0.74,
    createdAt: '2026-01-01T00:00:00Z',
  },
];

export const DEMO_ACHIEVEMENT_STATS = {
  total: DEMO_ACHIEVEMENTS.length,
  secret: DEMO_ACHIEVEMENTS.filter(a => a.isSecret).length,
  seasonal: DEMO_ACHIEVEMENTS.filter(a => a.isSeasonal).length,
  crossPlatform: DEMO_ACHIEVEMENTS.filter(a => a.isCrossPlatform).length,
  totalUnlocks: DEMO_ACHIEVEMENTS.reduce((s, a) => s + a.unlockedCount, 0),
  avgUnlockRate: DEMO_ACHIEVEMENTS.reduce((s, a) => s + a.unlockRate, 0) / DEMO_ACHIEVEMENTS.length,
};
